#!/bin/bash
source /usr/lib/openfoam/openfoam2012/etc/bashrc
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#
(
	#clean
	rm -r openfoam/0.* openfoam/[1-9]*
	#run
	unbuffer pimpleFoam -case openfoam |tee pimpleFoam.log
)

#------------------------------------------------------------------------------
